# -*- coding: utf-8 -*-
"""lab_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/philhetzel/opan5510-class7/blob/main/lab_exercise.ipynb

# Diamond Company Analytics Challenge

**Time:** 35 minutes

**Scenario:** You are the new data analyst at a prestigious diamond company. The CEO has called an urgent meeting and needs answers to critical business questions about the inventory.

**Your Mission:** Analyze the diamond inventory data and provide insights to guide strategic decisions.
"""

import polars as pl

# Load the diamonds dataset
print("Loading diamonds dataset...")
df = pl.read_csv('https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/diamond.csv')
print("Dataset loaded successfully!")

"""## Section 1: Initial Inventory Assessment (5 minutes)

The CEO walks in: "Before we dive into specifics, I need to understand what we're working with. Give me the basics about our inventory database."

### Question 1: "How extensive is our inventory database?"

The CEO needs to know the scale of data you're analyzing.
"""

# Number of diamonds in the inventory
total_diamonds = len(df)
print(f"Total number of diamonds in inventory: {total_diamonds}")

"""### Question 2: "What information do we track about each diamond?"

List all the characteristics we record.
"""

# List all columns to see what characteristics are recorded for each diamond
diamond_columns = df.columns
print("Characteristics tracked for each diamond:")
print(diamond_columns)

"""### Question 3: "When I look at one line in this database, what am I looking at?"

Explain in business terms:

A grain is what each row represents, each row corresponds to one diamond with all its recorded characteritics.

**Your answer:** Each row represents:

## Section 2: Strategic Business Questions (20 minutes)

The CEO continues: "Now let's get to the important questions. Our board meeting is tomorrow and I need concrete numbers."

### Question 4: "We're considering expanding our storage facilities. How many total carats do we have in inventory? I need to know if our vaults can handle the weight."

Think about what measurement would help answer this.
"""

# Compute total carats in inventory
total_carats = df.select(
    pl.col("Carat Weight").sum().alias("total_carats")
).item()

print(f"Total carats in inventory: {total_carats:.2f} carats")

"""### Question 5: "Our new marketing campaign claims we have 'the widest variety of cuts in the industry.' Can you verify this?"

The CEO wants to know about variety, not quantity.
"""

# Count the number of unique cuts
unique_cuts = df.select(
    pl.col("Cut").n_unique().alias("num_unique_cuts")
).item()

# Show what the unique cuts are
cut_list = df.select(pl.col("Cut").unique().sort()).to_series().to_list()

print(f"Number of unique cuts: {unique_cuts}")
print(f"Cut types: {cut_list}")

"""### Question 6: "I'm meeting with our insurance company. They need to know our price exposure - what's our most and least valuable diamond?"
"""

# Find the most valuable diamond
max_price = df.select(pl.col("Price").max()).item()
most_expensive = df.filter(pl.col("Price") == max_price)

# Find the least valuable diamond
min_price = df.select(pl.col("Price").min()).item()
least_expensive = df.filter(pl.col("Price") == min_price)

print(f"Most expensive diamond: ${max_price:,.2f}")
most_expensive.select(["Carat Weight", "Cut", "Color", "Clarity", "Price"])

print(f"\nLeast expensive diamond: ${min_price:,.2f}")
least_expensive.select(["Carat Weight", "Cut", "Color", "Clarity", "Price"])

"""### Question 7: "Which color grades should we focus on in our premium line? I need typical prices across our color spectrum."

The CEO wants to understand pricing patterns.
"""

# Compute average price for each color grade
avg_price_by_color = (
    df.group_by("Color")
      .agg(
          pl.col("Price").mean().alias("avg_price"),
          pl.len().alias("count")  # Optional: number of diamonds per color
      )
      .sort("avg_price", descending=True)
)

print("Average price by color grade (highest to lowest):")
avg_price_by_color

"""**Reflection:** After analyzing by color, how has your view of the data changed? What does each row in your result represent now?

**Your answer:** New grain =

## Section 3: Advanced Strategic Analysis (10 minutes)

The CEO leans forward: "These next questions will shape our strategy for next year."

### Question 8: "We're thinking of specializing in certain clarity grades. For our investor deck, I need a complete breakdown showing: how many diamonds we have in each clarity grade, their typical price, and the total carats we're holding for each grade."
"""

# Compute breakdown by clarity grade
clarity_analysis = (
    df.group_by("Clarity")
      .agg(
          pl.len().alias("num_diamonds"),            # number of diamonds
          pl.col("Price").mean().alias("avg_price"), # typical price
          pl.col("Carat Weight").sum().alias("total_carats")  # total carats
      )
      .sort("avg_price", descending=True)  # optional: sort by value
)

print("Clarity grade analysis:")
clarity_analysis

"""### Question 9: "My luxury competitor claims they have the best prices for every cut-color combination. Show me our pricing structure across these combinations - I want to see where we're competitive."
"""

# Compute average price for each cut and color combination
cut_color_pricing = (
    df.group_by(["Cut", "Color"])
      .agg(
          pl.col("Price").mean().alias("avg_price"),      # typical price
          pl.len().alias("num_diamonds"),                # number of diamonds
          pl.col("Carat Weight").sum().alias("total_carats") # total carats
      )
      .sort("avg_price", descending=True)  # optional: sort by price
)

print("Average price per cut and color combination:")
cut_color_pricing

"""**Reflection:** How specific is your analysis now? What level of detail does each row represent?

**Your answer:** New grain =

### Question 10: URGENT - "Our biggest client is interested in purchasing entire inventory segments. They asked: 'Which color-cut combinations represent your highest total inventory value?' Show me the top 5 most valuable inventory segments by total worth, and include how many diamonds are in each segment."

This is critical for tomorrow's negotiation.
"""

# Compute total inventory value for each cut-color combination
inventory_value_segments = (
    df.group_by(["Cut", "Color"])
      .agg(
          (pl.col("Price") * pl.col("Carat Weight")).sum().alias("total_value"),  # total worth
          pl.len().alias("num_diamonds"),                                         # number of diamonds
          pl.col("Carat Weight").sum().alias("total_carats")                      # total carats
      )
      .sort("total_value", descending=True)
      .head(5)  # Top 5 segments
)

print("Top 5 most valuable inventory segments by cut and color:")
inventory_value_segments

"""## Debrief

Congratulations! You've just completed your first day as the diamond company's data analyst.

Remember:
- CEOs speak in business language, not technical terms
- Always understand what each row represents before analyzing
- Business questions contain clues about which operations to use
"""